services:
  qdrant:
    image: qdrant/qdrant:v1.16.1
    ports:
      - "6333:6333"
      - "6334:6334"
    ulimits:
      nofile: 65535
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 32G
    volumes:
      - qdrant_storage:/qdrant/storage

  qdrant_f16:
    image: qdrant/qdrant:v1.16.1
    ports:
      - "6333:6333"
      - "6334:6334"
    ulimits:
      nofile: 65535
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 32G
    volumes:
      - qdrant_f16_storage:/qdrant/storage

volumes:
  qdrant_storage:
    driver: local
  qdrant_f16_storage:
    driver: local
